#!/usr/bin/env bash
# Install nginx and start
apt-get -y install nginx
service nginx start
ufw allow 'Nginx HTTP'
echo "Hello World!\n" | sudo tee /var/www/html/index-debian.html
service nginx restart
