#!/usr/bin/env bash
# Range(1-101) "FizzBuzz" = multiple 5 and 3
# "Fizz" = multiple of 3, and 
# "Buzz" = multiple of 5
# Otherwise the nums is displayed

i=1

while [ $i -le 100 ]; do
    if [ $((i%5)) -eq 0 ] && [ $((i%3)) -eq 0 ]; 
    then
	    echo "FizzBuzz"
    elif [ $((i%5)) -eq 0 ];
    then
	    echo "Buzz"
    elif [ $((i%3)) -eq 0 ];
    then
	    echo "Fizz"
    else
	    echo "$i"
    fi
    i=$((i+1))
done